{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set version = VERSION %}
{% set project = pyproject['project'] %}

package:
  name: dynamont
  version: {{ version }}

source:
  path: ..

build:
  script:
    - mkdir -p build && cd build
    - rm -rf *
    - cmake ${SRC_DIR} -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_BUILD_TYPE=Release
    - make -j${CPU_COUNT}
    - make install
    - cd ..
    - {{ PYTHON }} -m pip install --no-build-isolation --no-deps --ignore-installed -vv .

requirements:
  build:
    - cmake
    - make
    - gtest # Add GTest to the build requirements
    - {{ compiler('cxx') }}  # This ensures the correct C++ compiler is used
    - pip
    - python
  host:
    - python
    - pip
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python
    {% for dep in project['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  source_files:
    - test
    # - $PREFIX/bin  # Ensure binaries are in the PATH
  requires:
    {% for dep in project['optional-dependencies']['test'] %}
    - {{ dep.lower() }}
    {% endfor %}
  commands:
    - dynamont-NT --help
    - dynamont-NTC --help
    - dynamont-resquiggle --help
    - dynamont-train --help
    - test_dynamont
    - pytest -vv


about:
  home: {{ project['urls']['repository'] }}
  summary: {{ project['description'] }}
  license: {{ pyproject.get('license') }}
  license_file: LICENSE
  description: |
    {{ project['description'] }}

extra:
  recipe-maintainers:
    - JannesSP